import type { Translations } from '@/src/i18n/types';

export const translations: Translations = {
  pt: {
    'common.loading': 'Carregando...', 'common.back': 'Voltar', 'common.save': 'Salvar', 'common.cancel': 'Cancelar', 'common.search': 'Buscar', 'common.scanNow': 'Escanear agora', 'common.analyzeProduct': 'Analisar produto', 'common.understandProduct': 'Entender este produto',
    'onboarding.title': 'Decisões inteligentes na palma da mão', 'onboarding.subtitle': 'Escaneie rótulos, compare opções e compre com mais segurança.', 'onboarding.benefit1Title': 'Leitura instantânea', 'onboarding.benefit1Desc': 'Aponte a câmera e receba uma análise rápida.', 'onboarding.benefit2Title': 'Metodologia clara', 'onboarding.benefit2Desc': 'Score transparente de 0 a 100 com critérios objetivos.', 'onboarding.benefit3Title': 'Histórico estratégico', 'onboarding.benefit3Desc': 'Salve, compare e evolua suas escolhas.', 'onboarding.cta': 'Começar minha análise', 'onboarding.trust': 'Aviso: o app auxilia decisões e não substitui orientação profissional.',
    'auth.loginTitle': 'Bem-vindo de volta', 'auth.loginSubtitle': 'Entre para continuar suas análises e recomendações.', 'auth.email': 'E-mail', 'auth.password': 'Senha', 'auth.login': 'Entrar e continuar', 'auth.loggingIn': 'Entrando...', 'auth.createAccount': 'Criar conta grátis', 'auth.registerTitle': 'Criar conta', 'auth.registerSubtitle': 'Comece grátis e tenha mais clareza nas suas compras.', 'auth.name': 'Nome', 'auth.register': 'Criar minha conta', 'auth.registering': 'Criando conta...', 'auth.forgotPassword': 'Esqueci minha senha', 'auth.forgotTitle': 'Recuperar senha', 'auth.forgotSubtitle': 'Enviaremos um link seguro para redefinição.', 'auth.sendReset': 'Enviar link de recuperação', 'auth.sendingReset': 'Enviando...', 'auth.resetSent': 'Se o e-mail existir, enviamos o link de recuperação.', 'auth.emptyEmail': 'Informe seu e-mail para continuar.',
    'home.title': 'Olá! Vamos escolher melhor hoje?', 'home.subtitle': 'Compare produtos em segundos e compre com confiança.', 'home.manualSearch': 'Busca inteligente', 'home.featured': 'Produto em destaque', 'home.quickAccess': 'Acesso rápido', 'home.methodology': 'Metodologia: score baseado em ingredientes, processamento e composição nutricional.', 'home.socialProof': 'Prova social: espaço reservado para depoimentos reais de usuários.',
    'search.title': 'Busca inteligente', 'search.subtitle': 'Digite o nome e descubra alternativas mais claras.', 'search.placeholder': 'Ex.: granola sem açúcar', 'search.empty': 'Digite um termo para começar sua análise.',
    'scanner.title': 'Scanner inteligente', 'scanner.subtitle': 'Leia códigos EAN-13 e entenda o produto antes de comprar.', 'scanner.permissionTitle': 'Permissão de câmera', 'scanner.permissionSubtitle': 'Precisamos da câmera para análise automática.', 'scanner.manualTitle': 'Análise manual', 'scanner.manualSubtitle': 'Digite o código de barras para continuar.',
    'institutional.faqTitle': 'Perguntas frequentes', 'institutional.contactTitle': 'Contato', 'institutional.privacyTitle': 'Privacidade', 'institutional.termsTitle': 'Termos de uso', 'institutional.contactEmail': 'E-mail: contato@rotula.app', 'institutional.contactWhatsapp': 'WhatsApp: +55 (11) 99999-9999',
    'cta.premiumTitle': 'Pronto para comprar com mais segurança?', 'cta.premiumDescription': 'Use o scanner e receba uma leitura clara da composição em segundos.', 'cta.premiumButton': 'Escanear agora'
  },
  en: {
    'common.loading': 'Loading...', 'common.back': 'Back', 'common.save': 'Save', 'common.cancel': 'Cancel', 'common.search': 'Search', 'common.scanNow': 'Scan now', 'common.analyzeProduct': 'Analyze product', 'common.understandProduct': 'Understand this product',
    'onboarding.title': 'Smarter decisions in your pocket', 'onboarding.subtitle': 'Scan labels, compare options, and buy with confidence.', 'onboarding.benefit1Title': 'Instant reading', 'onboarding.benefit1Desc': 'Point your camera and get quick analysis.', 'onboarding.benefit2Title': 'Clear methodology', 'onboarding.benefit2Desc': 'Transparent 0-100 score with objective criteria.', 'onboarding.benefit3Title': 'Strategic history', 'onboarding.benefit3Desc': 'Save, compare, and improve your choices.', 'onboarding.cta': 'Start my analysis', 'onboarding.trust': 'Disclaimer: app supports decisions and does not replace professionals.',
    'auth.loginTitle': 'Welcome back', 'auth.loginSubtitle': 'Sign in to continue your analysis journey.', 'auth.email': 'Email', 'auth.password': 'Password', 'auth.login': 'Sign in and continue', 'auth.loggingIn': 'Signing in...', 'auth.createAccount': 'Create free account', 'auth.registerTitle': 'Create account', 'auth.registerSubtitle': 'Start free and shop with more clarity.', 'auth.name': 'Name', 'auth.register': 'Create my account', 'auth.registering': 'Creating account...', 'auth.forgotPassword': 'Forgot password', 'auth.forgotTitle': 'Reset password', 'auth.forgotSubtitle': 'We will send a secure reset link.', 'auth.sendReset': 'Send reset link', 'auth.sendingReset': 'Sending...', 'auth.resetSent': 'If the email exists, we sent a reset link.', 'auth.emptyEmail': 'Please enter your email.',
    'home.title': 'Hi! Ready to choose better today?', 'home.subtitle': 'Compare products in seconds and buy with confidence.', 'home.manualSearch': 'Smart search', 'home.featured': 'Featured product', 'home.quickAccess': 'Quick access', 'home.methodology': 'Method: score based on ingredients, processing and nutrition.', 'home.socialProof': 'Social proof: reserved space for real user testimonials.',
    'search.title': 'Smart search', 'search.subtitle': 'Type a name and discover clearer alternatives.', 'search.placeholder': 'Ex.: sugar free granola', 'search.empty': 'Type a term to start your analysis.',
    'scanner.title': 'Smart scanner', 'scanner.subtitle': 'Read EAN-13 codes and understand products before buying.', 'scanner.permissionTitle': 'Camera permission', 'scanner.permissionSubtitle': 'We need your camera for automatic analysis.', 'scanner.manualTitle': 'Manual analysis', 'scanner.manualSubtitle': 'Type the barcode to continue.',
    'institutional.faqTitle': 'Frequently asked questions', 'institutional.contactTitle': 'Contact', 'institutional.privacyTitle': 'Privacy', 'institutional.termsTitle': 'Terms of use', 'institutional.contactEmail': 'Email: contact@rotula.app', 'institutional.contactWhatsapp': 'WhatsApp: +1 (000) 000-0000',
    'cta.premiumTitle': 'Ready to shop with confidence?', 'cta.premiumDescription': 'Use the scanner and get clear composition insights in seconds.', 'cta.premiumButton': 'Scan now'
  },
};
